/* 
Copyright (c) 2009-2010 Konnetic Ltd.
*/
/* Change history
* 20 Jan 2010  James Wright james@konnetic.com Baseline Implementation
*/

using System;
using System.ComponentModel;

namespace Konnetic.Sip.Headers
{
    /// <summary>The From HeaderField indicates the initiator of the request.
    /// </summary>
    /// <remarks> 
    /// <b>Standards: RFC3261</b>
    /// <para/>
    /// The initiator of the request may be different from the initiator of the dialog. Requests sent by the callee to the caller use the callee's address in the From HeaderField.
    /// <para/>
    /// The optional display-name is meant to be rendered by a human user interface. A system should use the display name "Anonymous" if the identity of the client is to remain hidden. Even if the display-name is empty, the name-addr form must be used if the addr-spec contains a comma, question mark, or semicolon.
    /// <para/>
    /// The display name can be tokens, or a quoted string, if a larger character set is desired. Even if the display-name is empty, the name-addr form must be used if the addr-spec contains a comma, semicolon, or question mark. There may or may not be WHITESPACE between the display-name and the "&lt;". These rules for parsing a display name, URI and URI parameters, and header parameters also apply for the HeaderFields To and From.
    /// <para/>
    /// Two From HeaderFields are equivalent if their URIs match, and their parameters match. Extension parameters in one HeaderField, not present in the other are ignored for the purposes of comparison. This means that the display name and presence or absence of angle brackets do not affect matching.
    /// <para/>
    /// <b>URI</b>
    /// The Contact, From, and To HeaderFields contain a URI. If the URI contains a comma, question mark or semicolon, the URI must be enclosed in angle brackets (&lt; and &gt;). Any URI parameters are contained within these brackets. If the URI is not enclosed in angle brackets, any semicolon-delimited parameters are header-parameters, not URI parameters.
    /// <para/>
    /// <b>Tag Parameter</b>
    /// <para/>
    /// The tag parameter is used in the To and From HeaderFields of SIP messages. It serves as a general mechanism to identify a dialog, which is the combination of the Call-ID along with two tags, one from each participant in the dialog. When a client sends a request outside of a dialog, it contains a From tag only, providing "half" of the dialog ID. The dialog is completed from the response(s), each of which contributes the second half in the To HeaderField. The forking of SIP requests means that multiple dialogs can be established from a single request. This also explains the need for the two-sided dialog identifier; without a contribution from the recipients, the originator could not disambiguate the multiple dialogs established from a single request.
    /// <para/>
    /// When a tag is generated by a client for insertion into a request or response, it must be globally unique and cryptographically random with at least 32 bits of randomness. A property of this selection requirement is that a client will place a different tag into the From header of an INVITE than it would place into the To header of the response to the same INVITE. This is needed in order for a client to invite itself to a session, a common case for "hairpinning" of calls in PSTN gateways. Similarly, two INVITEs for different calls will have different From tags, and two responses for different calls will have different To tags. 
    /// <para/>
    /// Besides the requirement for global uniqueness, the algorithm for generating a tag is implementation-specific. Tags are helpful in fault tolerant systems, where a dialog is to be recovered on an alternate server after a failure. A server can select the tag in such a way that a backup can recognize a request as part of a dialog on the failed server, and therefore determine that it should attempt to recover the dialog and any other state associated with it.
    /// <para/>
    /// <b>RFC 3261 Syntax:</b> 
    /// <table >
    /// <tr><td colspan="2" style="border-bottom:none">( "From" / "f" ) ":" ( name-addr / addr-spec ) *( SEMI from-param )</td></tr> 
    /// <tr><td style="border-bottom:none">name-addr = </td><td style="border-bottom:none">[ display-name ] &lt; addr-spec &gt;</td></tr>
    /// <tr><td style="border-bottom:none">addr-spec = </td><td style="border-bottom:none">SIP-URI / SIPS-URI / absoluteURI</td></tr>
    /// <tr><td style="border-bottom:none">display-name = </td><td style="border-bottom:none">*(token LWS)/ quoted-string</td></tr>
    /// <tr><td style="border-bottom:none">from-param = </td><td style="border-bottom:none">"tag" EQUAL token / generic-param</td></tr>
    /// <tr><td style="border-bottom:none">generic-param = </td><td style="border-bottom:none">token [ EQUAL token / host / quoted-string ]</td></tr>
    /// <tr><td style="border-bottom:none">token = </td><td style="border-bottom:none">1*(alphanum / "-" / "." / "!" / "%" / "*" / "_" / "+" / "‘" / "'" / "˜" )</td></tr>
    /// <tr><td style="border-bottom:none">quoted-string = </td><td style="border-bottom:none">SWS DOUBLE_QUOTE *(qdtext / quoted-pair ) DOUBLE_QUOTE</td></tr>
    /// <tr><td style="border-bottom:none">qdtext = </td><td style="border-bottom:none">LWS / %x21 / %x23-5B / %x5D-7E / UTF8-NONASCII</td></tr>
    /// <tr><td style="border-bottom:none">LWS = </td><td style="border-bottom:none">[*WSP CRLF] 1*WSP ; linear whitespace</td></tr>
    /// <tr><td style="border-bottom:none">SWS = </td><td style="border-bottom:none">[LWS] ; sep whitespace</td></tr>
    /// <tr><td style="border-bottom:none">host = </td><td style="border-bottom:none">hostname / IPv4address / IPv6reference</td></tr>
    /// </table>  
    /// <para/>
    /// <note type="implementnotes">The compact form of the From HeaderField is "f".</note> 
    /// <para/>
    /// <note type="implementnotes">This HeaderField does not allow HeaderField grouping.</note> 
    /// <example>
    /// <list type="bullet">
    /// <item>From: "A. G. Bell" &lt;sip:agb@bell-telephone.com&gt; ;tag=a48s</item> 
    /// <item>From: sip:+12125551212@server.phone2net.com;tag=887s</item> 
    /// <item>f: Anonymous &lt;sip:c8oqz84zk7z@privacy.org&gt;;tag=hyh8</item> 
    /// </list> 
    /// </example>
    /// </remarks> 
    /// <seealso cref="T:Konnetic.Sip.Headers.TagAddressedHeaderFieldBase"/>
    /// <seealso cref="T:Konnetic.Sip.Headers.ToHeaderFieldBase"/>
    /// <seealso cref="T:Konnetic.Sip.Headers.ContactHeaderFieldBase"/>
    public sealed class FromHeaderField : TagAddressedHeaderFieldBase
    {
        #region Fields

    /// <summary>
    /// 
    /// </summary>
        internal const string CompareName = "FROM";
        /// <summary>
        /// 
        /// </summary>
        internal const string CompareShortName = "F";

        /// <summary>
        /// The long form of the name.
        /// </summary>
        internal const string LongName = "From";

        /// <summary>
        /// The short form of the name.
        /// </summary>
        internal const string ShortName = "f";

        /// <summary>
        /// Represents whether the user wishes to remain hidden.
        /// </summary>
        /// <remarks>The system will display the name "Anonymous" if the user is hidden.</remarks>
        private bool _remainHidden;

        #endregion Fields

        #region Properties
        /// <summary>
        /// Gets the generic parameters.
        /// </summary>
        /// <value>A <see cref="T:System.Collections.ObjectModel.ReadOnlyCollection&lt;SipParameter&gt;"/> field parameter.</value>
        public System.Collections.ObjectModel.ReadOnlyCollection<SipParameter> GenericParameters
            {
            get { return InternalGenericParameters; }
            }
        /// <summary>
        /// Adds the parameter.
        /// </summary>
        /// <param name="name">The name.</param>
        /// <param name="value">The value.</param>
        public void AddParameter(string name, string value)
            {
            InternalAddGenericParameter(name, value);
            }
        /// <summary>
        /// Adds the parameter.
        /// </summary>
        /// <param name="parameter">The parameter.</param>
        public void AddParameter(SipParameter parameter)
            {
            InternalAddGenericParameter(parameter);
            }
        /// <summary>
        /// Gets or sets the display name.
        /// </summary>
        /// <value>The display name.</value>
        public override string DisplayName
        {
            get
                {
                return RemainHidden ? "Anonymous" : base.DisplayName;
                }
            set
            {
            base.DisplayName = value;
                }
        }

        /// <summary>
        /// Gets or sets a value indicating whether [remain hidden].
        /// </summary>
        /// <value><c>true</c> if remain hidden; otherwise, <c>false</c>.</value>
        /// <remarks>The system will display the name "Anonymous" if the user is hidden.</remarks>
        [DefaultValue(false)]
        public bool RemainHidden
            {
            [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.U1)]
            get { return _remainHidden; }
            set
            {
            _remainHidden = value;
            }
        }

        #endregion Properties

        #region Constructors

		/// <summary>
		/// Initializes a new instance of the <see cref="FromHeaderField"/> class.
        /// </summary>
        /// <remarks>The default constructor. <para/>
        /// <b>Default Initializations:</b>
        /// <list type="bullet">
        /// <item><see cref="P:Sip.Konnetic.Headers.FromHeaderField.Tag" /> is set to a new random value.</item>  
        /// </list> </remarks>
		/// <overloads>
		/// <summary>The method has four overloads.</summary>
		/// </overloads>
		public FromHeaderField() 
			{ 
			Init();
            RecreateTag();
			}
        /// <summary>
        /// Initializes a new instance of the <see cref="FromHeaderField"/> class.
        /// </summary>
        /// <param name="uri">The initiator's URI string.</param>
        public FromHeaderField(string uri)
            : this(new SipUri(uri))
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FromHeaderField"/> class.
        /// </summary>
        /// <param name="uri">The initiator's URI.</param>
        public FromHeaderField(SipUri uri)
            : this(uri, string.Empty)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FromHeaderField"/> class.
        /// </summary>
        /// <param name="uri">The initiator's URI.</param>
        /// <param name="displayName">The initiator's display name.</param>
        public FromHeaderField(SipUri uri, string displayName)
            : this(uri, displayName, string.Empty)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="FromHeaderField"/> class.
        /// </summary>
        /// <param name="uri">The initiator's URI.</param>
        /// <param name="displayName">The initiator's display name.</param>
        /// <param name="tag">The tag parameter.</param>
        public FromHeaderField(SipUri uri, string displayName, string tag)
            : base(uri, displayName)
        {
			PropertyVerifier.ThrowOnNullArgument(tag, "tag");
			Init();
            Tag =tag;
        }

 

        #endregion Constructors

        #region Methods

		/// <summary>
		/// Performs an implicit conversion from <see cref="System.String"/> to <see cref="Konnetic.Sip.Headers.FromHeaderField"/>.
		/// </summary>
		/// <param name="value">The string value representing the HeaderField.</param>
        /// <returns>A new <see cref="Konnetic.Sip.Headers.FromHeaderField"/> populated from the <paramref name="value"/> parameter.</returns>
        /// <exception cref="ArgumentNullException">Thrown on null (<b>Nothing</b> in Visual Basic) <paramref name="value"/>.</exception>
        public static implicit operator FromHeaderField(String value)
        {
            PropertyVerifier.ThrowOnNullArgument(value,"value");

            FromHeaderField hf = new FromHeaderField();
            hf.Parse(value);
            return hf;
        }

		/// <summary>
		/// Performs an explicit conversion from <see cref="Konnetic.Sip.Headers.FromHeaderField"/> to <see cref="System.String"/>.
		/// </summary>
		/// <param name="headerField">The HeaderField to convert.</param>
		/// <returns>A string representation of the HeaderField.</returns>
		/// <exception cref="ArgumentNullException">Thrown on null (<b>Nothing</b> in Visual Basic) <paramref name="headerField"/>.</exception>
        public static explicit operator string(FromHeaderField headerField)
        {
            PropertyVerifier.ThrowOnNullArgument(headerField, "headerField");
            return headerField.ToString();
        }


        /// <summary>
        /// Creates a deap  copy of this instance.
        /// </summary> 
        /// <remarks>Creates and returns a deep copy of the Header. This method ensures a deep copy of the HeaderField, when a message is cloned the HeaderField can be modified without effecting the original HeaderField in the message.</remarks>
        /// <returns>A deep copy of <see cref="T:Konnetic.Sip.Headers.FromHeaderField"/>.</returns>
        /// <threadsafety static="true" instance="false" /> 
public override HeaderFieldBase Clone()
        {
        FromHeaderField newObj = new FromHeaderField(Uri, DisplayName);
        CopyParametersTo(newObj);  
            newObj._remainHidden = _remainHidden;
            newObj.UriSet = UriSet;
            return newObj;
        }
/// <summary>Compare this SIP Header for equality with the base <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/>.
/// </summary>
/// <remarks>This method overrides the <c>equals</c> method in <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/>. 
/// All optional headers are compared using object equality that is each field in the header is used for comparision. When comparing HeaderFields, field names are always case-insensitive. Unless otherwise stated in the definition of a particular HeaderField, field values, parameter names, and parameter values are case-insensitive. Tokens are always case-insensitive. Unless specified otherwise, values expressed as quoted strings are case-sensitive. 
/// </remarks>
/// <param name="other">The <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/> to compare to this instance.</param>
/// <returns><c>true</c> if <paramref name="other" /> is an instance of this class representing the same SIP HeaderField as this, <c>false</c> otherwise.</returns>
/// <overloads>
/// <summary>This method is overloaded.</summary>
/// <remarks>Overloads allow for equality against <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/>, <see cref="T:System.Object"/> and another instance of this HeaderField.</remarks>
/// </overloads>  
/// <threadsafety static="true" instance="false" /> 
        [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.U1)]
        public override bool Equals(HeaderFieldBase other)
        {
            return Equals((object)other);
        }
        /// <summary>Compare this SIP Header for equality with an instance of <see cref="T:System.Object"/>.
        /// </summary>
        /// <remarks>This method overrides the <c>equals</c> method in <see cref="System.Object"/>. 
        /// All optional headers are compared using object equality that is each field in the header is used for comparision. When comparing HeaderFields, field names are always case-insensitive. Unless otherwise stated in the definition of a particular HeaderField, field values, parameter names, and parameter values are case-insensitive. Tokens are always case-insensitive. Unless specified otherwise, values expressed as quoted strings are case-sensitive. 
        /// </remarks>
        /// <param name="obj">The <see cref="T:System.Object"/> to compare to this instance.</param>
        /// <returns><c>true</c> if <paramref name="obj" /> is an instance of this class representing the same SIP HeaderField as this, <c>false</c> otherwise. </returns>        
        /// <overloads>
        /// <summary>This method is overloaded.</summary>
        /// <remarks>Overloads allow for equality against <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/>, <see cref="T:System.Object"/> and another instance of this HeaderField.</remarks>
        /// </overloads> 
        /// <threadsafety static="true" instance="false" />
        [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.U1)]
        public override bool Equals(object obj)
        {
            if(obj == null)
                {
                return false;
                }

            FromHeaderField p1 = obj as FromHeaderField;
            if((object)p1 == null)
                {
                HeaderFieldGroup<FromHeaderField> p = obj as HeaderFieldGroup<FromHeaderField>;
                if((object)p == null)
                    {
                    return false;
                    }
                else
                    {
                    return p.Equals(this);
                    }
                }
            else
                {
                return this.Equals(p1);
                }
        }

        /// <summary>
        /// Validates this instance against the standard. Indicated whether it reaches minimum compliance.
        /// </summary>
        /// <remarks>This member overrides the <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/> instance.</remarks>
        /// <returns>
        /// 	<c>true</c> if instance represents a valid HeaderField; otherwise, <c>false</c>.
        /// </returns>
        /// <threadsafety static="true" instance="false" />
        [return: System.Runtime.InteropServices.MarshalAs(System.Runtime.InteropServices.UnmanagedType.U1)]
        public override bool IsValid()
        {
            return base.IsValid() && !string.IsNullOrEmpty(Tag);
        }

        /// <summary>
        /// Parses string representation of the HeaderField.
        /// </summary>
        /// <remarks>  
        /// <b>RFC 3261 Syntax:</b> 
        /// <table >
        /// <tr><td colspan="2" style="border-bottom:none">( "From" / "f" ) ":" ( name-addr / addr-spec ) *( SEMI from-param )</td></tr> 
        /// <tr><td style="border-bottom:none">name-addr = </td><td style="border-bottom:none">[ display-name ] &lt; addr-spec &gt;</td></tr>
        /// <tr><td style="border-bottom:none">addr-spec = </td><td style="border-bottom:none">SIP-URI / SIPS-URI / absoluteURI</td></tr>
        /// <tr><td style="border-bottom:none">display-name = </td><td style="border-bottom:none">*(token LWS)/ quoted-string</td></tr>
        /// <tr><td style="border-bottom:none">from-param = </td><td style="border-bottom:none">"tag" EQUAL token / generic-param</td></tr>
        /// <tr><td style="border-bottom:none">generic-param = </td><td style="border-bottom:none">token [ EQUAL token / host / quoted-string ]</td></tr>
        /// <tr><td style="border-bottom:none">token = </td><td style="border-bottom:none">1*(alphanum / "-" / "." / "!" / "%" / "*" / "_" / "+" / "‘" / "'" / "˜" )</td></tr>
        /// <tr><td style="border-bottom:none">quoted-string = </td><td style="border-bottom:none">SWS DOUBLE_QUOTE *(qdtext / quoted-pair ) DOUBLE_QUOTE</td></tr>
        /// <tr><td style="border-bottom:none">qdtext = </td><td style="border-bottom:none">LWS / %x21 / %x23-5B / %x5D-7E / UTF8-NONASCII</td></tr>
        /// <tr><td style="border-bottom:none">LWS = </td><td style="border-bottom:none">[*WSP CRLF] 1*WSP ; linear whitespace</td></tr>
        /// <tr><td style="border-bottom:none">SWS = </td><td style="border-bottom:none">[LWS] ; sep whitespace</td></tr>
        /// <tr><td style="border-bottom:none">host = </td><td style="border-bottom:none">hostname / IPv4address / IPv6reference</td></tr>
        /// </table>  
        /// <para/>
        /// <note type="implementnotes">The compact form of the From HeaderField is "f".</note> 
        /// <para/>
        /// <note type="implementnotes">This HeaderField does not allow HeaderField grouping.</note> 
        /// <example>
        /// <list type="bullet">
        /// <item>From: "A. G. Bell" &lt;sip:agb@bell-telephone.com&gt; ;tag=a48s</item> 
        /// <item>From: sip:+12125551212@server.phone2net.com;tag=887s</item> 
        /// <item>f: Anonymous &lt;sip:c8oqz84zk7z@privacy.org&gt;;tag=hyh8</item> 
        /// </list> 
        /// </example>
        /// </remarks>
        /// <param name="value">The HeaderField string to parse.</param>
        /// <exception cref="T:Konnetic.Sip.SipParseException">Thrown when an invalid (non-standard) value is encountered.</exception>
        /// <exception cref="T:Konnetic.Sip.SipException">Thrown when a processing exception is encountered.</exception>
        /// <threadsafety static="true" instance="false" />
        public override void Parse(string value)
        {
            if(value != null)
                {
                RemoveFieldName(ref value, FieldName, CompactName);
                    base.Parse(value);
                }
        }

        /// <summary>
        /// Gets a string representation of the HeaderField value. The HeaderField name is excluded.
        /// </summary>
        /// <remarks>This method overrides the <c>GetStringValue</c> method in <see cref="T:Konnetic.Sip.Headers.HeaderFieldBase"/>. </remarks>
        /// <returns>String representation of the HeaderField value</returns>
        /// <threadsafety static="true" instance="false" />
        protected override string GetStringValueNoParams()
        {
            if(RemainHidden)
                {
                if(Uri.Scheme == "sips")
                {
                return SR.GetString(SR.SecureHiddenAddress);
                }
            else
                {
                return SR.GetString(SR.HiddenAddress);
                }

            }
            else
            {
            return base.GetStringValueNoParams();
            }
        }

        /// <summary>
        /// Initialises this instance.
        /// </summary>
        private void Init()
        {
            AllowMultiple = false;
            FieldName = FromHeaderField.LongName;
            CompactName = FromHeaderField.ShortName;
        }

        #endregion Methods
    }
}