//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4200
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Konnetic.Sip {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Konnetic.Sip.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the string value ({0}) to a byte for field value &apos;{1}&apos;..
        /// </summary>
        internal static string ByteConvertException {
            get {
                return ResourceManager.GetString("ByteConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter ({0}) already exists as a header field parameter..
        /// </summary>
        internal static string DuplicateHeaderParameter {
            get {
                return ResourceManager.GetString("DuplicateHeaderParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string argument cannot be null or zero length..
        /// </summary>
        internal static string EmptyString {
            get {
                return ResourceManager.GetString("EmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the string value ({0}) to a float for field value &apos;{1}&apos;..
        /// </summary>
        internal static string FloatConvertException {
            get {
                return ResourceManager.GetString("FloatConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Anonymous&quot;.
        /// </summary>
        internal static string FromHeaderFieldHiddenDisplayName {
            get {
                return ResourceManager.GetString("FromHeaderFieldHiddenDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured whilst parsing value ({0}) for for field value &apos;{1}&apos;..
        /// </summary>
        internal static string GeneralParseException {
            get {
                return ResourceManager.GetString("GeneralParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot add duplicate field (&apos;{0}&apos;) to HeaderFieldCollection. Use a group instead..
        /// </summary>
        internal static string HeaderFieldDuplicate {
            get {
                return ResourceManager.GetString("HeaderFieldDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Anonymous&quot; &lt;sip:unknown@private&gt;.
        /// </summary>
        internal static string HiddenAddress {
            get {
                return ResourceManager.GetString("HiddenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal characters found in parameter name..
        /// </summary>
        internal static string IllegalParameterNameException {
            get {
                return ResourceManager.GetString("IllegalParameterNameException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert the string value ({0}) to an integer for field value&apos;{1}&apos;..
        /// </summary>
        internal static string IntegerConvertException {
            get {
                return ResourceManager.GetString("IntegerConvertException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} must be a valid host. .
        /// </summary>
        internal static string InvalidHostString {
            get {
                return ResourceManager.GetString("InvalidHostString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} must be a valid IPAddress..
        /// </summary>
        internal static string InvalidIPAddressString {
            get {
                return ResourceManager.GetString("InvalidIPAddressString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password parameter contains illegal characters. Check for &apos;@&apos;,&apos;?&apos;,&apos;/&apos;,&apos;;&apos; and &apos;:&apos; characters..
        /// </summary>
        internal static string InvalidPasswordString {
            get {
                return ResourceManager.GetString("InvalidPasswordString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} must be a (optionally quoted) comma seperated list of tokens. (token = alphanum / &quot;-&quot; / &quot;.&quot; / &quot;!&quot; / &quot;%&quot; / &quot;*&quot;
        //// &quot;_&quot; / &quot;+&quot; / &quot;‘&quot; / &quot;&apos;&quot; / &quot;˜&quot;).
        /// </summary>
        internal static string InvalidQuotedTokenWithCommaString {
            get {
                return ResourceManager.GetString("InvalidQuotedTokenWithCommaString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} must be a token. (token = alphanum / &quot;-&quot; / &quot;.&quot; / &quot;!&quot; / &quot;%&quot; / &quot;*&quot;
        //// &quot;_&quot; / &quot;+&quot; / &quot;‘&quot; / &quot;&apos;&quot; / &quot;˜&quot;).
        /// </summary>
        internal static string InvalidTokenString {
            get {
                return ResourceManager.GetString("InvalidTokenString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username contains illegal characters. Ensure the username does not contain an unescaped &apos;:&apos; or &apos;@&apos; character..
        /// </summary>
        internal static string InvalidUsernameString {
            get {
                return ResourceManager.GetString("InvalidUsernameString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection supplied should not contain null member..
        /// </summary>
        internal static string NullCollectionMember {
            get {
                return ResourceManager.GetString("NullCollectionMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is out of the expected range {1}..{2}..
        /// </summary>
        internal static string OutOfRangeByte {
            get {
                return ResourceManager.GetString("OutOfRangeByte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is out of the expected range {1}..{2}..
        /// </summary>
        internal static string OutOfRangeDouble {
            get {
                return ResourceManager.GetString("OutOfRangeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ({0}) is too large  for field value &apos;{1}&apos; which expects values between {2} and {3}..
        /// </summary>
        internal static string OutOfRangeException {
            get {
                return ResourceManager.GetString("OutOfRangeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is out of the expected range {1}..{2}..
        /// </summary>
        internal static string OutOfRangeFloat {
            get {
                return ResourceManager.GetString("OutOfRangeFloat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value {0} is out of the expected range {1}..{2}..
        /// </summary>
        internal static string OutOfRangeLong {
            get {
                return ResourceManager.GetString("OutOfRangeLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter {0} out of range..
        /// </summary>
        internal static string OutOfRangeParameter {
            get {
                return ResourceManager.GetString("OutOfRangeParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The length for parameter {0} is out of the expected range {1}..{2}..
        /// </summary>
        internal static string OutOfRangeString {
            get {
                return ResourceManager.GetString("OutOfRangeString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value ({0}) is too large  for field value &apos;{1}&apos;..
        /// </summary>
        internal static string OverflowException {
            get {
                return ResourceManager.GetString("OverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The string was not correctly formatted to parse ({0})..
        /// </summary>
        internal static string ParseException {
            get {
                return ResourceManager.GetString("ParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An exception occured when parsing property &apos;{0}&apos;..
        /// </summary>
        internal static string PropertyParseException {
            get {
                return ResourceManager.GetString("PropertyParseException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Anonymous&quot; &lt;sips:unknown@private&gt;.
        /// </summary>
        internal static string SecureHiddenAddress {
            get {
                return ResourceManager.GetString("SecureHiddenAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Code..
        /// </summary>
        internal static string Warning0 {
            get {
                return ResourceManager.GetString("Warning0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more network protocols contained in the session description are not available..
        /// </summary>
        internal static string Warning300 {
            get {
                return ResourceManager.GetString("Warning300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more network address formats contained in the session description are not available..
        /// </summary>
        internal static string Warning301 {
            get {
                return ResourceManager.GetString("Warning301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more transport protocols described in the session description are not available..
        /// </summary>
        internal static string Warning302 {
            get {
                return ResourceManager.GetString("Warning302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more bandwidth measurement units contained in the session description were not understood..
        /// </summary>
        internal static string Warning303 {
            get {
                return ResourceManager.GetString("Warning303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more media types contained in the session description are not available..
        /// </summary>
        internal static string Warning304 {
            get {
                return ResourceManager.GetString("Warning304", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more media formats contained in the session description are not available..
        /// </summary>
        internal static string Warning305 {
            get {
                return ResourceManager.GetString("Warning305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more of the media attributes in the session description are not supported..
        /// </summary>
        internal static string Warning306 {
            get {
                return ResourceManager.GetString("Warning306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter other than those listed above was not understood..
        /// </summary>
        internal static string Warning307 {
            get {
                return ResourceManager.GetString("Warning307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site where the user is located does not support multicast..
        /// </summary>
        internal static string Warning330 {
            get {
                return ResourceManager.GetString("Warning330", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site where the user is located does not support unicast communication..
        /// </summary>
        internal static string Warning331 {
            get {
                return ResourceManager.GetString("Warning331", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bandwidth specified in the session description or defined by the media exceeds that known to be available..
        /// </summary>
        internal static string Warning370 {
            get {
                return ResourceManager.GetString("Warning370", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The warning text can include arbitrary information to be presented to a human user or logged..
        /// </summary>
        internal static string Warning399 {
            get {
                return ResourceManager.GetString("Warning399", resourceCulture);
            }
        }
    }
}
